### ISSUE TITLE
Fallback Content

### ISSUE THREAD

**Issue by deniaz** [merkle-open/drupal-terrific-micro#4]
The data array to be consumed by the template is generated here: https://github.com/namics/drupal-terrific/blob/8.x/src/Adapter/ContextProvider.php#L87

So if you wanted to load nitro's `data.json` you could for example add that after `L101` (if no data was found).

An alternative, which could also help with your `t` problem, is writing a `NodeVisitor`, like [here](http://kriswallsmith.net/post/15421960092/twig-node-visitors-part-2). With that you could detect all used variables and provide a default/fallback value at compilation time.

**Comment by grahl** [comment]
❤️
